version: '3.8'

services:
  # Redis service for job queue
  redis:
    image: redis:7-alpine
    container_name: crawl4ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # MCP Server (API)
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8051
    container_name: crawl4ai-server
    ports:
      - "8051:8051"
    env_file:
      - .env
    environment:
      - TRANSPORT=sse
      - HOST=0.0.0.0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped

  # Background Workers (2 replicas for parallel processing)
  crawl-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    deploy:
      replicas: 2

volumes:
  redis_data: